return {
	"hrsh7th/cmp-nvim-lsp",
-- 	config = function ()
-- 		capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)
-- local lspconfig = require("lspconfig")
--
-- lspconfig.templ.setup{
--   on_attach = on_attach,
--   capabilities = capabilities,
-- }
--
-- lspconfig.tailwindcss.setup({
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "templ", "astro", "javascript", "typescript", "react" },
--   init_options = { userLanguages = { templ = "html" } },
-- })
--
-- lspconfig.html.setup({
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "html", "templ" },
-- })
--
-- lspconfig.htmx.setup({
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "html", "templ" },
-- })
--
-- local cmp = require 'cmp'
-- cmp.setup({
--   mapping = cmp.mapping.preset.insert({
--     ['<C-b>'] = cmp.mapping.scroll_docs(-4),
--     ['<C-f>'] = cmp.mapping.scroll_docs(4),
--     ['<C-Space>'] = cmp.mapping.complete(),
--     ['<C-e>'] = cmp.mapping.abort(),
--     ['<CR>'] = cmp.mapping.confirm({ select = true }),
--   }),
--   sources = cmp.config.sources({
--     { name = 'nvim_lsp' },
--   })
-- })
-- 		
-- 	end
}
